version: '3.9'

services:
  mysql:
    image: mysql:5.7 # down to speed
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: platia
      MYSQL_USER: user123
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  springboot:
    build: .
    container_name: springboot
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_USER: user123
      MYSQL_PASSWORD: pass123
    ports:
      - "8080:8080"

volumes:
  mysql_data:
