version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123!@#
      MYSQL_DATABASE: mydb
      MYSQL_USER: user123
      MYSQL_PASSWORD: abc123!@#
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d 

  springboot:
    build: .
    container_name: springboot
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_USER: user123
      MYSQL_PASSWORD: abc123!@#
    ports:
      - "8080:8080"

volumes:
  mysql_data:

